apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: flaskapp
  name: flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
status: {}
