apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
